# Generated by Django 5.0.6 on 2024-05-17 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='foto_perfil',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
